checks:
  go: true
build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      environment:
        go:
          version: go1.9.2
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run
          - command: tree /home/scrutinizer/gopath/src/github.com/yakult1995/go-posgre-restapi/
    tests:
      environment:
        go:
          version: go1.9.2
          go_import_path: github.com/yakult1995/go-posgre-restapi/app/
      tests:
        override:
          - command: go test -v /go/src/github.com/yakult1995/go-posgre-restapi
    coverage:
      tests:
        override:
          - command: go test -coverprofile=cover.out
            coverage:
              file: 'cover.out'
              format: 'go-cc'
