#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"<<-EOSQL
     CREATE USER $POSTGRES_TEST_USER WITH PASSWORD '$POSTGRES_TEST_PASSWORD';
     ALTER ROLE $POSTGRES_TEST_USER SUPERUSER;
     ALTER DATABASE $POSTGRES_DB SET timezone TO 'Asia/Tokyo';
EOSQL
